config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :networks do
    member do
      post :increase
      post :decrease
    end
    resources :waterpoints, only: [:index, :new, :create, :edit, :update]
  end
  resources :tasks do
    patch :completed, on: :member
    collection do
      get :export, defaults: { format: :csv }
    end
    resources :comments, only: [:new, :create, :edit]
  end
  resources :waterpoints, only: [:destroy]
  resources :equipments do
    collection do
      get :export, defaults: { format: :csv }
    end
  end
  resources :services
  resources :comments, only: [:update, :destroy]
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'technicians', to: 'users#index', as: :technicians
  patch 'users/:id/user_status', to: 'users#user_status', as: :user_status
  get 'statistics', to: 'pages#stats', as: :stats
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :issuer, class_name: "User", foreign_key: "issuer_id"
  belongs_to :technician, class_name: "User", foreign_key: "technician_id"
  belongs_to :equipment
  belongs_to :waterpoint
  belongs_to :network
  belongs_to :service
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :title, presence: true
  validates :extra_info, presence: true
  validates :technician, presence: true
  validates :service, presence: true
  validates :equipment, presence: true
  validates :waterpoint, presence: true

  paginates_per 12
  include PgSearch::Model
  pg_search_scope :search_by_fields,
                  against: [:title],
                  associated_against: {
                    technician: [:first_name, :last_name],
                    network: [:name]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_and_authorize_equipment, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = policy_scope(Task)
    @tasks = policy_scope(Task).search_by_fields(params[:query]).page params[:page] if params[:query].present?
    @tasks = @tasks.where(completed: false) if params[:hide_complete].present?
    @tasks = @tasks.where(unscheduled: true) if params[:hide_predicted].present?
    @tasks = @tasks.where(technician: current_user) unless current_user.manager
    @tasks = @tasks.order(end_date: :asc).page params[:page]
  end

  def show
    @task = Task.find(params[:id])
    @comment = Comment.new
  end

  def new
    @task = Task.new
    authorize @task
    @technician = User.where(technician: true).all
  end

  def create
    @task = Task.new(task_params)
    authorize @task
    @task.network = Waterpoint.find(task_params[:waterpoint_id]).network if task_params[:waterpoint_id].present?
    @task.issuer = current_user
    if @task.save
      redirect_to task_path(@task)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  def completed
    @task = Task.find(params[:id])
    @task.update(task_params)
    authorize @task

    new_task = @task.attributes.except("id", "completion_date", "completed", "created_at", "updated_at", "unscheduled")
    repeated_task = Task.new(new_task)
    repeated_task.start_date = @task.completion_date + @task.service.frequency.months
    days_between_start_and_end = (@task.end_date - @task.start_date).to_i / 86400
    repeated_task.end_date = repeated_task.start_date + days_between_start_and_end.days
    repeated_task.unscheduled = false

    repeated_task.save

    redirect_to task_path(@task)
  end

  def export
    @tasks = policy_scope(Task)
    authorize @tasks

    respond_to do |format|
      format.csv do
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = "attachment; filename=tasks.csv"
      end
    end
  end

  private

  def find_and_authorize_equipment
    @task = Task.find(params[:id])
    authorize @task
  end

  def task_params
    params.require(:task).permit(:start_date, :end_date, :title, :extra_info, :unscheduled, :service_id, :technician_id, :waterpoint_id, :equipment_id, :completion_date, :completed)
  end
end

app/views/tasks/edit.html.erb
<section class="mw-800 mb-3">
  <div class="f-wrapper">
    <h1 class="d-title mb-5 w-100">AMEND TASK</h1>
    <div class="f-container">
      <%= simple_form_for @task, data: { controller: 'flatpickr' } do |f| %>
        <div class="row mt-4">
          <div class="col-12 col-md-6">
            <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startDate" } } %>
          </div>
          <div class="col-12 col-md-6">
            <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endDate" } } %>
          </div>
        </div>
        <%= f.input :title %>
        <%= f.input :extra_info %>
        <%= f.association :technician,
          as: :radio_buttons,
          collection: User.where(:manager => false),
          label_method: lambda { |technician| "#{technician.first_name.upcase} #{technician.last_name.upcase}" },
          collection_wrapper_tag: 'div',
          collection_wrapper_class: 'category-wrapper',
          item_wrapper_class: 'category-item',
          input_html: {class: 'category-selector'} %>
        <div>
          <%= f.association :service %>
        </div>
        <div data-service-equipment-target='serviceInput'>
          <%= f.association :equipment %>
        </div>
        <%= f.association :waterpoint, :label_method => lambda { |waterpoint| "#{waterpoint.waterpoint_type} at #{waterpoint.network.name}" } %>
        <%= f.input :completion_date, as: :string, input_html: { data: { flatpickr_target: "completedDate" } } %>
        <%= f.button :submit, 'AMEND TASK', class: "primary-btn mt-4" %>
      <% end %>
    </div>
  </div>
</section>

app/views/tasks/export.csv.erb
<% headers = ['ID',
              'TASK',
              'TECHNICIAN',
              'ISSUER',
              'START_DATE',
              'DUE DATE',
              'NETWORK',
              'SERVICE',
              'SCHEDULED',
              'STATUS'] %>
<%= CSV.generate_line(headers, row_sep: "") %>
<% @tasks.each do |task| %>
  <% task_line = ["#{task.id}",
                  "#{task.title.upcase}",
                  "#{task.technician.full_name.upcase}",
                  "#{task.issuer.full_name.upcase}",
                  "#{task.start_date.strftime('%d/%m/%Y')}",
                  "#{task.end_date.strftime('%d/%m/%Y')}",
                  "#{task.network.name.upcase} #{task.waterpoint.waterpoint_type.upcase}",
                  "#{task.service.name.upcase}",
                  "#{task.unscheduled ? "UNSCHEDULED" : "SCHEDULED"}",
                  "#{task.completed ? "COMPLETED" : "INCOMPLETE"}"
                 ] %>
  <%= CSV.generate_line(task_line, row_sep: "") %>
<% end %>

app/views/tasks/index.html.erb
<div class="w-view" data-controller="tooltips">
  <section class="mw-800 d-flex justify-content-between mb-3">
    <%= form_with url: tasks_path, method: :get, class: "search-form" do %>
      <%= text_field_tag :query, params[:query], class: "form-control search-bar", placeholder: "Find a task" %>
      <div class="d-flex justify-content-center align-items-center">
        <%= check_box_tag :hide_complete, params[:hide_complete], params[:hide_complete], { label: "sdfsdfsf", onchange: "this.form.submit()" } %>
        <%= label_tag :hide_complete, 'HIDE COMPLETE TASKS', class: 'ms-1' %>
        <%= check_box_tag :hide_predicted, params[:hide_predicted], params[:hide_predicted], { label: "sdfsdfsf", onchange: "this.form.submit()", class: 'ms-3' } %>
        <%= label_tag :hide_predicted, 'HIDE SCHEDULED TASKS', class: 'ms-1' %>
      </div>
    <% end %>
    <%#= link_to 'ADD TASK', new_task_path, class: 'secondary-btn' if policy(Task).new? %>
  </section>
  <section class="mw-800 mb-3">
    <div class="t-six border-bottom mb-4">
      <h6 class="headers">TASK</h6>
      <h6 class="headers">TECHNICIAN</h6>
      <h6 class="headers">DUE DATE</h6>
      <h6 class="headers">NETWORK</h6>
      <h6 class="headers">SCHEDULED</h6>
      <h6 class="headers e-active">STATUS</h6>
    </div>
    <% @tasks.each do |task| %>
      <div class="network">
        <%= link_to task_path(task), class: 'text-decoration-none' do %>
          <div class="t-six">
            <p><%= task.title.upcase %></p>
            <p><%= task.technician.full_name.upcase %></p>
            <p><%= task.end_date.strftime('%d/%m/%Y') %></p>
            <p><%= task.network.name.upcase %></p>
            <p class="bold <%= task.unscheduled ? 'text-red' : 'text-green' %>"><%= task.unscheduled ? "REACTIVE" : "SCHEDULED" %></p>
            <% if task.completion_date %>
              <span class="e-active" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Completed on <%= task.completion_date.strftime("%a, %e %b %Y") %>">
            <% else %>
              <span class="e-active">
            <% end %>
              <p class="ms-3 <%= task.completed ? 'task-green' : 'task-red' %>"></p>
            </span>
          </div>
        <% end %>
        <% if policy(task).new? %>
          <div class="menu-options dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            •••
          </div>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "EDIT", edit_task_path(task), class: "dropdown-item" %>
            <%= link_to "DELETE", task_path(task), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete the task #{task.title}?"}, class: "dropdown-item" %>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="pag-cont border-top mt-4">
      <div class="page-entry">
        <%= page_entries_info @tasks %>
      </div>
      <%= paginate @tasks %>
      <%= link_to export_tasks_path, class: "csv-btn" do %>
        DOWNLOAD TO CSV <i class="bi bi-arrow-down-short"></i>
      <% end %>
    </div>
  </section>
</div>

<!------------- MOBILE ------------->
<!------------- VIEW ------------->
<!------------- BELOW ------------->

<div class="m-view" data-controller="tooltips">
  <h4 class="d-title mb-3">TASKS</h4>
  <section class="mb-3">
    <%= form_with url: tasks_path, method: :get, class: "search-form" do %>
      <%= text_field_tag :query, params[:query], class: "form-control search-bar", placeholder: "Find a task" %>
      <div class="ms-2 d-flex">
        <%= check_box_tag :hide_complete, params[:hide_complete], params[:hide_complete], { label: "sdfsdfsf", onchange: "this.form.submit()", class: 'me-1' } %>
        <%= label_tag :hide_complete, 'HIDE COMPLETE TASKS' %>
      </div>
      <div class="ms-2 d-flex">
        <%= check_box_tag :hide_predicted, params[:hide_predicted], params[:hide_predicted], { label: "sdfsdfsf", onchange: "this.form.submit()", class: 'me-1' } %>
        <%= label_tag :hide_predicted, 'HIDE SCHEDULED TASKS' %>
      </div>
    <% end %>
    <%#= link_to 'ADD TASK', new_task_path, class: 'secondary-btn' if policy(Task).new? %>
  </section>

  <div class="page-entry text-center mb-3">
    <%= page_entries_info @tasks %>
  </div>

  <% @tasks.each do |task| %>
    <section class="m-card">
      <%= link_to task_path(task), class: 'text-decoration-none' do %>
        <div class="">
          <p class="bold"><%= task.title.upcase %></p>
          <hr>
          <div class="d-flex align-items-center mb-3">
            <% if task.technician.avatar.attached? %>
              <%= cl_image_tag task.technician.avatar.key, class: "avatar me-2" %>
            <% else %>
              <div class="m-ai me-2">
                <%= task.technician.initials %>
              </div>
            <% end %>
            <p class="mb-0"><%= task.technician.full_name.upcase %></p>
          </div>
          <div class="d-flex align-items-center mb-3">
            <%= image_tag 'card-cal.png', class: 'card-i' %><p class="mb-0"><%= task.end_date.strftime('%d/%m/%Y') %></p>
          </div>
          <div class="d-flex align-items-center mb-3">
            <%= image_tag 'card-tap.png', class: 'card-i' %><p class="mb-0"><%= task.network.name.upcase %> <%= task.waterpoint.waterpoint_type.upcase %></p>
          </div>
          <p class="m-tag me-1 <%= task.unscheduled ? 'red-bg' : 'green-bg' %>"><%= task.unscheduled ? "REACTIVE" : "SCHEDULED" %></p>
          <% if !task.completed && Date.today > task.end_date %>
            <p class="m-tag red-bg">OVERDUE</p>
          <% else %>
            <p class="m-tag <%= task.completed ? 'green-bg' : 'red-bg' %>"><%= task.completed ? 'COMPLETED' : 'INCOMPLETE' %></p>
          <% end %>
        </div>
      <% end %>
      <% if policy(task).new? %>
        <div class="menu-options dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          •••
        </div>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to "EDIT", edit_task_path(task), class: "dropdown-item" %>
          <%= link_to "DELETE", task_path(task), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete the task #{task.title}?"}, class: "dropdown-item" %>
        </div>
      <% end %>
    </section>
  <% end %>

  <div class="pag-cont border-top">
    <%= paginate @tasks %>
    <%#= link_to export_tasks_path, class: "csv-btn mt-3" do %>
      <!-- DOWNLOAD TO CSV <i class="bi bi-arrow-down-short"></i> -->
    <%# end %>
  </div>

</div>

app/views/tasks/new.html.erb
<section class="mw-800 mb-3 pb-5">
  <%= simple_form_for @task, data: { controller: 'flatpickr' } do |f| %>
    <div class="f-wrapper">
      <div class="d-flex justify-content-between w-100 ">
        <h1 class="d-title mb-5 mt-1">ASSIGN TASK</h1>
        <%= f.input :unscheduled, label: "REACTIVE" %>
      </div>
      <div class="f-container">
          <div class="row mt-4">
            <div class="col-12 col-md-6">
              <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startDate" } } %>
            </div>
            <div class="col-12 col-md-6">
              <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endDate" } } %>
            </div>
          </div>
          <%= f.input :title %>
          <%= f.input :extra_info, label: "Details" %>
          <%= f.association :technician,
            as: :radio_buttons,
            collection: User.where(:manager => false),
            label_method: lambda { |technician| "#{technician.first_name.upcase} #{technician.last_name.upcase}" },
            collection_wrapper_tag: 'div',
            collection_wrapper_class: 'category-wrapper',
            item_wrapper_class: 'category-item',
            input_html: {class: 'category-selector'} %>
          <%= f.association :service %>
          <%= f.association :equipment %>
          <%= f.association :waterpoint, :label_method => lambda { |waterpoint| "#{waterpoint.network.name} #{waterpoint.waterpoint_type}" } %>
          <%= f.button :submit, 'ADD TASK', class: "primary-btn mt-4" %>
      </div>
    </div>
  <% end %>
</section>

app/views/tasks/show.html.erb
<div data-controller="tasks">
  <div class="w-view">
    <div class="tasks-wrapper">
      <div class="d-flex mw-800 mb-3">
        <div class="t-info">
          <div class="d-flex justify-content-between mb-3">
            <div class="me-3">
              <h4 class="mb-3 d-title">
                <%= @task.title.upcase %>
                <% if policy(Task).new? %>
                  <span class="d-flex my-3">
                    <%= link_to edit_task_path(@task), class: 'option-link' do %>
                      <i class="bi bi-pen-fill"></i>
                    <% end %>
                    <%= link_to task_path(@task), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete the network #{@task.title}?"}, class: 'option-link' do %>
                      <i class="bi bi-trash3-fill"></i>
                    <% end %>
                  </span>
                <% end %>
                <% if !@task.completed && policy(@task).completed? %>
                  <section>
                    <p class="headers d-flex justify-content-center">TASK COMPLETED ON</p>
                    <%= simple_form_for @task, url: completed_task_path(@task), method: :patch, data: { controller: 'flatpickr',turbo_confirm: "Are you sure you want to mark this task as complete?" } do |f| %>
                      <div class="d-flex flex-column justify-content-center align-items-center">
                        <%= f.input :completion_date, as: :string, label: false, placeholder: "This task was completed on...", wrapper_html: { class: 'mb-1 w-100' }, input_html: { data: { flatpickr_target: "completedDate" } } %>
                        <%= f.input_field :completed, as: :hidden, value: true %>
                        <%= f.submit "COMPLETE TASK", class: "primary-btn task-completed-btn mx-1" %>
                      </div>
                    <% end %>
                    <%#= link_to "COMPLETE TASK", completed_task_path(@task), class: "primary-btn mt-3" %>
                  </section>
                <% end %>
              </h4>
              <p class="text-green mb-1"><span class="bold">TECHNICIAN:</span> <%= @task.technician.full_name.upcase %></p>
              <p class="text-green"><span class="bold">ASSIGNED BY:</span> <%= @task.issuer.full_name.upcase %></p>
              <span class="task-tag me-2">
                <p class="<%= @task.completed ? 'task-green' : 'task-red' %> mb-0 me-2"></p>
                <% if !@task.completed && Date.today > @task.end_date %>
                  <p class="mb-0">OVERDUE</p>
                <% else %>
                  <p class="mb-0"><%= @task.completed ? 'COMPLETED' : 'INCOMPLETE' %></p>
                <% end %>
              </span>
              <span class="task-tag">
                <p class="<%= @task.unscheduled ? 'task-red' : 'task-green' %> mb-0 me-2"></p>
                <p class="mb-0"><%= @task.unscheduled ? " REACTIVE" : "SCHEDULED" %></p>
              </span>
              <% if @task.completion_date %>
                <p class="mb-0 mt-3"><strong class="headers">COMPLETED ON:</strong> <%= @task.completion_date.strftime("%a, %e %b %Y") %></p>
              <% end %>
            </div>
            <div class="t-dates">
              <section class="me-3">
                <p class="text-green mb-1">START DATE</p>
                <p class="text-green bold mb-0"><%= @task.start_date.strftime('%d/%m/%Y') %></p>
              </section>
              <section>
                <p class="text-green mb-1">DUE DATE</p>
                <p class="text-green bold mb-0"><%= @task.end_date.strftime('%d/%m/%Y') %></p>
              </section>
            </div>
          </div>


          <section class="details">
            <h6 class="headers pb-3 mb-3 border-bottom">DETAILS</h6>
            <p><%= @task.extra_info %></p>
          </section>
        </div>
      </div>
      <hr>
      <section class="mb-3">
        <div class="d-flex justify-content-between align-items-center">
          <h6 class="headers mb-0">COMMENTS</h6>
          <%= link_to 'ADD COMMENT', new_task_comment_path(@task), class: 'secondary-btn' if policy(Comment).new? %>
        </div>
        <% @task.comments.each_with_index do |comment, index| %>
          <div class="border-top mt-3 pt-3 pe-3 c-card">
            <p class="ps-3 mb-1"><%= comment.content %></p>
            <% if comment.photos.attached? %>
              <% comment.photos.each do |photo| %>
                <%= cl_image_tag photo.key, class: 'c-imgs', data: { bs_toggle: "modal", bs_target: "#expandImg", action: "click->tasks#expand" } %>
              <% end %>
            <% end %>
            <p class="ps-3 c-time">posted by <strong><%= comment.user.full_name %></strong> <%= time_ago_in_words(comment.created_at) %> ago</p>
            <% if policy(comment).edit? %>
              <div class="menu-options dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                •••
              </div>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "EDIT", edit_task_comment_path(@task, comment), class: "dropdown-item" %>
                <%= link_to "DELETE", comment_path(comment), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "dropdown-item" %>
              </div>
            <% end %>
          </div>
        <% end %>
      </section>
    </div>
  </div>

  <div class="m-view">
    <div class="mb-3">
      <div class="me-3 mb-3">
        <h4 class="mb-3 d-title">
          <%= @task.title.upcase %>
          <% if policy(Task).new? %>
            <span class="d-flex my-3">
              <%= link_to edit_task_path(@task), class: 'option-link' do %>
                <i class="bi bi-pen-fill"></i>
              <% end %>
              <%= link_to task_path(@task), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete the network #{@task.title}?"}, class: 'option-link' do %>
                <i class="bi bi-trash3-fill"></i>
              <% end %>
            </span>
          <% end %>
          <% if !@task.completed && policy(@task).completed? %>
            <section class="completed-form-m">
              <p class="headers d-flex justify-content-center">TASK COMPLETED ON</p>
              <%= simple_form_for @task, url: completed_task_path(@task), method: :patch, data: { controller: 'flatpickr' } do |f| %>
                <div class="d-flex flex-column justify-content-center align-items-center">
                  <%= f.input :completion_date, as: :string, label: false, wrapper_html: { class: 'mb-1 w-100' }, input_html: { data: { flatpickr_target: "completedDateMobile" }, value: Date.today } %>
                  <%= f.input_field :completed, as: :hidden, value: true %>
                  <%= f.submit "COMPLETE TASK", class: "primary-btn task-completed-btn mx-1" %>
                </div>
              <% end %>
            </section>
          <% end %>
        </h4>
        <p class="text-green mb-1"><span class="bold">TECHNICIAN:</span> <%= @task.technician.full_name.upcase %></p>
        <p class="text-green"><span class="bold">ASSIGNED BY:</span> <%= @task.issuer.full_name.upcase %></p>
        <span class="task-tag me-2">
          <p class="<%= @task.completed ? 'task-green' : 'task-red' %> mb-0 me-2"></p>
          <% if !@task.completed && Date.today > @task.end_date %>
            <p class="mb-0">OVERDUE</p>
          <% else %>
            <p class="mb-0"><%= @task.completed ? 'COMPLETED' : 'INCOMPLETE' %></p>
          <% end %>
        </span>
        <span class="task-tag">
          <p class="<%= @task.unscheduled ? 'task-red' : 'task-green' %> mb-0 me-2"></p>
          <p class="mb-0"><%= @task.unscheduled ? " REACTIVE" : "SCHEDULED" %></p>
        </span>
        <% if @task.completion_date %>
          <p class="mb-0 mt-3"><strong class="headers">COMPLETED ON:</strong> <%= @task.completion_date.strftime("%a, %e %b %Y") %></p>
        <% end %>
      </div>

      <div class="g-two">
        <section>
          <p class="text-green text-center mb-1">START DATE</p>
          <p class="text-green text-center bold mb-0"><%= @task.start_date.strftime('%d/%m/%Y') %></p>
        </section>
        <section>
          <p class="text-green text-center mb-1">DUE DATE</p>
          <p class="text-green text-center bold mb-0"><%= @task.end_date.strftime('%d/%m/%Y') %></p>
        </section>
      </div>
    </div>

    <section class="details">
      <h6 class="headers pb-3 mb-3 border-bottom">DETAILS</h6>
      <p><%= @task.extra_info %></p>
    </section>
    <hr>
    <section class="mb-3">
      <div class="d-flex justify-content-between align-items-center">
        <h6 class="headers mb-0">COMMENTS</h6>
        <%= link_to 'ADD COMMENT', new_task_comment_path(@task), class: 'secondary-btn' if policy(Comment).new? %>
      </div>
      <% @task.comments.each_with_index do |comment, index| %>
        <div class="border-top mt-3 pt-3 pe-3 c-card">
          <p class="ps-3 mb-1"><%= comment.content %></p>
          <% if comment.photos.attached? %>
            <% comment.photos.each do |photo| %>
              <%= cl_image_tag photo.key, class: 'c-imgs', data: { bs_toggle: "modal", bs_target: "#expandImg", action: "click->tasks#expand" } %>
            <% end %>
          <% end %>
          <p class="ps-3 c-time">posted by <strong><%= comment.user.full_name %></strong> <%= time_ago_in_words(comment.created_at) %> ago</p>
          <% if policy(comment).edit? %>
            <div class="menu-options dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              •••
            </div>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "EDIT", edit_task_comment_path(@task, comment), class: "dropdown-item" %>
              <%= link_to "DELETE", comment_path(comment), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "dropdown-item" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </section>
  </div>

  <!-- Modal -->
  <!-- Below -->

  <div class="modal fade" id="expandImg" tabindex="-1" aria-labelledby="expandLabel" aria-hidden="true">
    <div class="modal-dialog">
      <!-- <div class="modal-content"> -->
          <img data-tasks-target="image" src="" alt="">
      <!-- </div> -->
    </div>
  </div>
</div>