config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :networks do
    member do
      post :increase
      post :decrease
    end
    resources :waterpoints, only: [:index, :new, :create, :edit, :update]
  end
  resources :tasks do
    patch :completed, on: :member
    collection do
      get :export, defaults: { format: :csv }
    end
    resources :comments, only: [:new, :create, :edit]
  end
  resources :waterpoints, only: [:destroy]
  resources :equipments do
    collection do
      get :export, defaults: { format: :csv }
    end
  end
  resources :services
  resources :comments, only: [:update, :destroy]
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'technicians', to: 'users#index', as: :technicians
  patch 'users/:id/user_status', to: 'users#user_status', as: :user_status
  get 'statistics', to: 'pages#stats', as: :stats
end

app/models/network.rb
class Network < ApplicationRecord
  has_many :waterpoints, dependent: :destroy
  has_many :tasks
  has_many :services, through: :tasks
  validates :name, presence: :true
  validates :address, presence: :true
  validates :number_of_households, presence: :true
  validates :max_households, presence: :true
  paginates_per 18
  include PgSearch::Model
  pg_search_scope :search_by_name,
                  against: [:name],
                  using: {
                    tsearch: { prefix: true }
                  }

  def completed_percentage
      result = (tasks.where(completed: true).count.to_f / tasks.count) * 100
      "#{result.round}%"
  end
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
  before_action :find_and_authorize_network, only: [:show, :edit, :update, :destroy]
  def index
    if params[:query].present?
      @networks = policy_scope(Network).search_by_name(params[:query]).page params[:page]
    else
      @networks = policy_scope(Network).page params[:page]
    end
  end

  def show
    @markers = @network.waterpoints.map do |waterpoint|
      {
        lat: waterpoint.latitude,
        lng: waterpoint.longitude,
        info_window: render_to_string(partial: "shared/info_window", locals: { waterpoint: waterpoint }),
      }
    end
    @equipments = @network.waterpoints.map(&:equipments).reject(&:blank?).flatten
  end

  def new
    @network = Network.new
    authorize @network
  end

  def create
    @network = Network.new(network_params)
    authorize @network
    if @network.save
      redirect_to network_path(@network)
    else
      render :new, status: :unprocessable_entity
    end
  end


  def edit
  end

  def update
    @network.update(network_params)
    redirect_to network_path(@network)
  end

  def destroy
    @network.destroy
    redirect_to networks_path, status: :see_other
  end

  private

  def find_and_authorize_network
    @network = Network.find(params[:id])
    authorize @network
  end

  def network_params
    params.require(:network).permit(:name, :address, :number_of_households, :max_households)
  end
end

app/views/networks/edit.html.erb
<section class="mw-800 mb-3">
  <div class="f-wrapper">
    <h1 class="d-title mb-5 w-100">AMEND NETWORK</h1>
    <div class="d-container">
      <%= simple_form_for @network do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :number_of_households %>
        <%= f.input :max_households %>
        <%= f.submit 'AMEND NETWORK', class: 'primary-btn' %>
      <% end %>
    </div>
  </div>
</section>

app/views/networks/index.html.erb
<div class="w-view">
  <section class="mw-800 d-flex justify-content-between mb-3">
    <%= form_with url: networks_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control search-bar",
        placeholder: "Find a network"
      %>
    <% end %>
    <%= link_to 'ADD NETWORK', new_network_path, class: 'secondary-btn' if policy(Network).new? %>
  </section>
  <div class="new-network-card-cont mb-3">
    <% @networks.each do |network| %>
      <%= link_to network_path(network), class: 'text-decoration-none' do %>
        <section class="new-network-card p-4">
          <h6 class="new-network-card__name"><%= network.name.upcase %></h6>
          <div>
            <p class="mb-0">HOUSEHOLD</p>
            <p class="mb-0">CONNECTIONS</p>
            <% if network.number_of_households == network.max_households %>
              <p class="text-red bold mb-0">FULL</p>
            <% else %>
              <p class="text-green bold mb-0"><%= network.number_of_households %>/<%= network.max_households %></p>
            <% end %>
          </div>
        </section>
      <% end %>
    <% end %>
  </div>
  <div class="pag-cont border-top mt-4">
    <div class="page-entry">
      <%= page_entries_info @networks %>
    </div>
    <%= paginate @networks %>
  </div>
</div>

<!------------- MOBILE ------------->
<!------------- VIEW ------------->
<!------------- BELOW ------------->

<div class="m-view">
  <h4 class="d-title mb-3">NETWORKS</h4>
  <section class="mb-3">
    <%= form_with url: networks_path, method: :get, class: "d-flex mb-2" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control search-bar",
        placeholder: "Find a network"
      %>
    <% end %>
    <%= link_to 'ADD NETWORK', new_network_path, class: 'secondary-btn' if policy(Network).new? %>
  </section>

  <div class="page-entry text-center mb-3">
    <%= page_entries_info @networks %>
  </div>

  <% @networks.each do |network| %>
    <%= link_to network_path(network), class: 'text-decoration-none' do %>
      <section class="new-network-card p-4">
        <h6 class="new-network-card__name"><%= network.name.upcase %></h6>
        <div>
          <p class="mb-0">HOUSEHOLD</p>
          <p class="mb-0">CONNECTIONS</p>
          <% if network.number_of_households == network.max_households %>
            <p class="text-red bold mb-0">FULL</p>
          <% else %>
            <p class="text-green bold mb-0"><%= network.number_of_households %>/<%= network.max_households %></p>
          <% end %>
        </div>
      </section>
    <% end %>
  <% end %>

  <div class="pag-cont border-top mt-4">
    <%= paginate @networks %>
  </div>

</div>

app/views/networks/new.html.erb
<section class="mw-800 mb-3">
  <%= simple_form_for @network do |f| %>
    <div class="f-wrapper">
      <div class="d-flex justify-content-between w-100 ">
        <h1 class="d-title mb-5 w-100">ADD NETWORK</h1>
      </div>
      <div class="f-container">
       <div class="row mt-4">
          <div class="col-6">
            <%= f.input :name %>
          </div>
          <div class="col-6">
            <%= f.input :address %>
          </div>
        </div>
        <%= f.input :number_of_households %>
        <%= f.input :max_households %>
        <%= f.submit 'ADD NETWORK', class: 'primary-btn mt-4' %>
      </div>
    </div>
  <% end %>
</section>

app/views/networks/show.html.erb
<div class="w-view">
  <h4 class="mb-3 headers d-flex align-items-center">
    <%= @network.name.upcase %> NETWORK
    <% if policy(Network).new? %>
      <span class="d-flex ms-3">
        <%= link_to edit_network_path(@network), class: 'option-link' do %>
          <i class="bi bi-pen-fill"></i>
        <% end %>
        <%= link_to network_path(@network), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete the network #{@network.name}?"}, class: 'option-link' do %>
          <i class="bi bi-trash3-fill"></i>
        <% end %>
      </span>
    <% end %>
  </h4>
  <div class="g-two mb-3">
    <div class="g-four">
      <section class="info-square">
        <p>NUMBER OF HOUSEHOLD CONNECTIONS</p>
        <% if @network.number_of_households == @network.max_households %>
          <span class="text-red">FULL</span>
        <% else %>
          <span class="text-green"><%= @network.number_of_households %>/<%= @network.max_households %></span>
        <% end %>
      </section>
      <section class="info-square">
        <p>NUMBER OF TASKS</p>
        <span><%= @network.tasks.any? ? @network.tasks.count : "N/A" %></span>
      </section>
      <section class="info-square">
        <p>STATUS COMPLETED TASKS</p>
        <span><%= @network.tasks.any? ? @network.completed_percentage : "N/A" %></span>
      </section>
      <section class="info-square">
        <p>NEXT MAINTENANCE</p>
        <span><%= @network.tasks.any? ? @network.tasks.first.start_date.strftime("%a, %e %b %Y") : "N/A" %></span>
      </section>
      <section class="g-four__100">
        <div class="d-flex justify-content-between align-items-center border-bottom pb-3 mb-3">
          <h6 class="headers mb-0 ps-3">WATERPOINTS</h6>
          <%= link_to 'ADD WATERPOINT', new_network_waterpoint_path(@network), class: 'secondary-btn' if policy(Waterpoint).new? %>
        </div>
        <div class="g-two p-3 border-bottom mb-4">
          <h6 class="headers">NAME</h6>
          <h6 class="headers">WATERPOINT TYPE</h6>
        </div>
        <% @network.waterpoints.each do |waterpoint| %>
          <div class="network">
            <div class="g-two p-3">
              <p><%= waterpoint.name.upcase %></p>
              <p><%= waterpoint.waterpoint_type.upcase %></p>
            </div>
            <% if policy(Waterpoint).new? %>
              <div class="menu-options dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                •••
              </div>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "EDIT #{waterpoint.name.upcase}", edit_network_waterpoint_path(@network, waterpoint), class: "dropdown-item" %>
                <%= link_to "DELETE #{waterpoint.name.upcase}", waterpoint_path(waterpoint), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete the waterpoint #{waterpoint.name}?"}, class: "dropdown-item" %>
              </div>
            <% end %>
          </div>
        <% end %>
      </section>
    </div>
    <div style="width: 100%; height: 100%;"
         data-controller="map"
         data-map-markers-value="<%= @markers.to_json %>"
         data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>


  <section class="mw-800 mb-3">
    <div class="e-grid border-bottom mb-4">
      <h6 class="headers e-id">ID</h6>
      <h6 class="headers">EQUIPMENT</h6>
      <h6 class="headers">WATERPOINT</h6>
      <h6 class="headers">MANUFACTURER</h6>
      <h6 class="headers">DATE OF INSTALLATION</h6>
      <h6 class="headers">WARRANTY</h6>
      <h6 class="headers e-active">ACTIVE</h6>
    </div>
    <% @equipments.each do |equipment| %>
      <div class="network">
        <%= link_to equipment_path(equipment), class: 'text-decoration-none' do %>
          <div class="e-grid">
            <p class="e-id"><%= equipment.id %></p>
            <p><%= equipment.name.upcase %></p>
            <p><%= equipment.waterpoint.name.upcase %> <%= equipment.waterpoint.waterpoint_type.upcase %></p>
            <p><%= equipment.manufacturer.upcase %></p>
            <p><%= equipment.date_of_installation.strftime('%d/%m/%Y') %></p>
            <p class="bold <%= Date.today > equipment.date_of_expiration ? 'text-red' : 'text-green' %>"><%= Date.today > equipment.date_of_expiration ? "EXPIRED" : "VALID" %></p>
            <span class="e-active">
              <p class="ms-3 <%= equipment.inactive ? 'task-red' : 'task-green' %>"></p>
            </span>
          </div>
        <% end %>
      </div>
    <% end %>
  </section>
</div>

<div class="m-view">
  <div class="mb-3">
    <h4 class="mb-0 d-title d-flex align-items-center"> <%= @network.name.upcase %> NETWORK</h4>
    <% if policy(Network).new? %>
      <span class="d-flex mt-2">
        <%= link_to edit_network_path(@network), class: 'option-link' do %>
          <i class="bi bi-pen-fill"></i>
        <% end %>
        <%= link_to network_path(@network), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete the network #{@network.name}?"}, class: 'option-link' do %>
          <i class="bi bi-trash3-fill"></i>
        <% end %>
      </span>
    <% end %>
  </div>

  <div class="g-four">
    <section class="info-square">
      <p>NUMBER OF HOUSEHOLD CONNECTIONS</p>
      <% if @network.number_of_households == @network.max_households %>
        <span class="text-red">FULL</span>
      <% else %>
        <span class="text-green"><%= @network.number_of_households %>/<%= @network.max_households %></span>
      <% end %>
    </section>
    <section class="info-square">
      <p>NUMBER OF TASKS</p>
      <span><%= @network.tasks.any? ? @network.tasks.count : "N/A" %></span>
    </section>
    <section class="info-square">
      <p>STATUS COMPLETED TASKS</p>
      <span><%= @network.tasks.any? ? @network.completed_percentage : "N/A" %></span>
    </section>
    <section class="info-square">
      <p>NEXT MAINTENANCE</p>
      <span><%= @network.tasks.any? ? @network.tasks.first.start_date.strftime("%a, %e %b %Y") : "N/A" %></span>
    </section>
  </div>
  <div style="width: 100%; height: 300px; margin: 16px 0;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <div class="d-flex justify-content-between align-items-center border-top pt-3 mb-3">
    <h4 class="d-title mb-0">WATERPOINTS</h4>
    <%= link_to 'ADD WATERPOINT', new_network_waterpoint_path(@network), class: 'secondary-btn' if policy(Waterpoint).new? %>
  </div>
  <% @network.waterpoints.each do |waterpoint| %>
    <section class="m-card">
      <p class="bold"><%= waterpoint.name.upcase %></p>
      <hr>
      <div class="d-flex align-items-center">
        <%= image_tag 'card-tap.png', class: 'card-i' %><p class="mb-0"><%= waterpoint.waterpoint_type.upcase %></p>
      </div>
      <% if policy(Waterpoint).new? %>
        <div class="menu-options dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          •••
        </div>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to "EDIT #{waterpoint.name.upcase}", edit_network_waterpoint_path(@network, waterpoint), class: "dropdown-item" %>
          <%= link_to "DELETE #{waterpoint.name.upcase}", waterpoint_path(waterpoint), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete the waterpoint #{waterpoint.name}?"}, class: "dropdown-item" %>
        </div>
      <% end %>
    </section>
  <% end %>
  <div class="d-flex justify-content-between align-items-center border-top pt-3 mb-3">
    <h4 class="d-title mb-0">EQUIPMENT</h4>
    <%= link_to 'ADD EQUIPMENT', new_equipment_path, class: 'secondary-btn' if policy(Equipment).new? %>
  </div>
  <% @equipments.each do |equipment| %>
    <%= link_to equipment_path(equipment), class: 'text-decoration-none' do %>
      <section class="m-card">
        <p class="bold"><%= equipment.name.upcase %></p>
        <hr>
        <div class="d-flex align-items-center mb-3">
          <%= image_tag 'card-tap.png', class: 'card-i' %><p class="mb-0"><%= equipment.waterpoint.network.name.upcase %> <%= equipment.waterpoint.waterpoint_type.upcase %></p>
        </div>
        <div class="d-flex align-items-center mb-3">
          <i class="bi bi-building"></i><p class="mb-0"><%= equipment.manufacturer.upcase %></p>
        </div>
        <div class="d-flex align-items-center mb-3">
          <i class="bi bi-calendar-week"></i><p class="mb-0"><%= equipment.date_of_installation.strftime('%d/%m/%Y') %></p>
        </div>
        <div class="d-flex align-items-center mb-3">
          <% if Date.today > equipment.date_of_expiration %>
            <i class="bi bi-shield-fill-x"></i>
            <p class="bold text-red mb-0">EXPIRED</p>
          <% else %>
            <i class="bi bi-shield-fill-check"></i>
            <p class="bold text-green mb-0">VALID</p>
          <% end %>
        </div>
        <p class="m-tag me-1 <%= equipment.inactive ? 'red-bg' : 'green-bg' %>"><%= equipment.inactive ? "INACTIVE" : "ACTIVE" %></p>
      </section>
    <% end %>
  <% end %>
</div>