config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :networks do
    member do
      post :increase
      post :decrease
    end
    resources :waterpoints, only: [:index, :new, :create, :edit, :update]
  end
  resources :tasks do
    patch :completed, on: :member
    collection do
      get :export, defaults: { format: :csv }
    end
    resources :comments, only: [:new, :create, :edit]
  end
  resources :waterpoints, only: [:destroy]
  resources :equipments do
    collection do
      get :export, defaults: { format: :csv }
    end
  end
  resources :services
  resources :comments, only: [:update, :destroy]
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'technicians', to: 'users#index', as: :technicians
  patch 'users/:id/user_status', to: 'users#user_status', as: :user_status
  get 'statistics', to: 'pages#stats', as: :stats
end

app/models/user.rb
class User < ApplicationRecord
  attr_writer :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_validation :default_email
  validates :phone, presence: true, uniqueness: true
  has_one_attached :avatar
  has_many :tasks, class_name: "Task", foreign_key: "technician_id"
  has_many :comments
  paginates_per 20

  def default_email
    unless manager
      self.email = "#{first_name.downcase}#{last_name.downcase}".gsub(/\s/, "") + "@warwanda.com"
    end
  end

  def login
    @login || self.phone || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions).where(["lower(phone) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:phone].nil?
        where(conditions).first
      else
        where(phone: conditions[:phone]).first
      end
    end
  end

  def active_for_authentication?
    super && self.active
  end

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  def initials
    "#{first_name.first}#{last_name.first}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @technicians = policy_scope(User).where(manager: false).order(last_name: :asc)
    @technicians = @technicians.page params[:page]
  end

  # def dashboard
  #   authorize current_user

  #   @my_tasks = Task.where(technician: current_user).order(end_date: :asc)

  #   @due_tasks = Task.where(end_date: Date.today).group(:completed).count
  #   @due_tasks = @due_tasks.transform_keys { |key| key == true ? "COMPLETED" : "INCOMPLETE" }

  #   @tasks = Task.all
  #   @complete = @tasks.where(completed: true).count
  #   @incomplete = @tasks.where(completed: false).count
  #   @tasks_per_month = @tasks.where(completed: true).and(@tasks.where('end_date > ? AND end_date < ?', Date.today.beginning_of_month, Date.today.end_of_month)).group_by_day_of_month(:end_date).count
  #   @tasks = @tasks.order(end_date: :asc)
  # end

  def user_status
    @user = User.find(params[:id])
    authorize @user
    if @user.update(active: @user.active ? false : true)
      redirect_to technicians_path
    else
      render "users/index", status: :unprocessable_entity
    end
  end
end

app/views/users/dashboard.html.erb
<div class="w-view">
  <div class="g-two mb-3">
    <section class="d-tt d-fixed-scroll p-3">
      <div class="d-flex justify-content-between align-items-center border-bottom pb-3 mb-3">
        <h6 class="headers mb-0 ps-3"><%= current_user.manager ? "MOST RECENT TASKS" : "MY TASKS"  %></h6>
        <%= link_to 'ALL TASKS', tasks_path, class: 'secondary-btn' %>
      </div>
      <div class="d-four border-bottom mb-4">
        <h6 class="headers">TASK</h6>
        <h6 class="headers">TECHNICIAN</h6>
        <h6 class="headers">DUE DATE</h6>
        <h6 class="headers">NETWORK</h6>
        <!-- <h6 class="headers">STATUS</h6> -->
      </div>
      <% (current_user.manager ? @tasks : @my_tasks).first(5).each do |task| %>
        <div class="network">
          <%= link_to task_path(task), class: 'text-decoration-none' do %>
            <div class="d-four">
              <p><%= task.title.upcase %></p>
              <p><%= task.technician.full_name.upcase %></p>
              <p><%= task.end_date.strftime('%d/%m/%Y') %></p>
              <p><%= task.network.name.upcase %></p>
              <!-- <p class="<%#= task.completed ? 'task-green' : 'task-red' %>"></p> -->
              <!-- <p><%#= task.schedule.upcase %></p> -->
            </div>
          <% end %>
          <% if policy(task).new? %>
            <div class="menu-options dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              •••
            </div>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "EDIT", edit_task_path(task), class: "dropdown-item" %>
              <%= link_to "DELETE", task_path(task), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete the task #{task.title}?"}, class: "dropdown-item" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </section>
    <section class="d-ot">
      <div class="d-flex justify-content-between align-items-center border-bottom pb-3 mb-3">
        <h6 class="headers mb-0 pe-2" style="width: 150px;">TASKS DUE BY TODAY</h6>
        <%= link_to 'ALL NETWORKS', networks_path, class: 'secondary-btn' %>
      </div>
      <%= pie_chart @due_tasks, donut: true, height: "280px", width: "280px", colors: ["#FD8B05", "#0073DE"] %>
    </section>
  </div>
  <section class="mb-3">
    <div class="d-flex justify-content-between align-items-center border-bottom pb-3 mb-3">
      <h6 class="headers mb-0">THIS MONTHS COMPLETED TASKS</h6>
      <%= link_to 'VIEW STATS', stats_path, class: 'secondary-btn' %>
    </div>
    <%= column_chart @tasks_per_month, colors: ["rgba(1, 115, 222, 1)"], legend: false, height: "220px", discrete: true, label: "TODAY'S TASKS"  %>
  </section>
</div>

<!------------- MOBILE ------------->
<!------------- VIEW ------------->
<!------------- BELOW ------------->

<div class="m-view">

  <div class="d-flex justify-content-between align-items-center pb-3">
    <h4 class="mb-0 d-title">TASKS DUE TODAY</h4>
  </div>
  <section class="m-card">
    <%= pie_chart @due_tasks, donut: true, height: "280px", width: "100%", colors: ["#FD8B05", "#0073DE"] %>
  </section>

  <% tasks = current_user.manager ? @tasks : @my_tasks %>
  <div class="d-flex justify-content-between align-items-center pb-3">
    <h4 class="mb-0 d-title">TODAY'S TASKS</h4>
    <%= link_to 'ALL TASKS', tasks_path, class: 'secondary-btn' %>
  </div>
  <% tasks.first(5).each do |task| %>
    <section class="m-card">
      <%= link_to task_path(task), class: 'text-decoration-none' do %>
        <div class="">
          <p class="bold"><%= task.title.upcase %></p>
          <hr>
          <div class="d-flex align-items-center mb-3">
            <% if task.technician.avatar.attached? %>
              <%= cl_image_tag task.technician.avatar.key, class: "avatar me-2" %>
            <% else %>
              <div class="m-ai me-2">
                <%= task.technician.initials %>
              </div>
            <% end %>
            <p class="mb-0"><%= task.technician.full_name.upcase %></p>
          </div>
          <div class="d-flex align-items-center mb-3">
            <%= image_tag 'card-cal.png', class: 'card-i' %><p class="mb-0"><%= task.end_date.strftime('%d/%m/%Y') %></p>
          </div>
          <div class="d-flex align-items-center mb-3">
            <%= image_tag 'card-tap.png', class: 'card-i' %><p class="mb-0"><%= task.network.name.upcase %> <%= task.waterpoint.waterpoint_type.upcase %></p>
          </div>
          <p class="m-tag me-1 <%= task.unscheduled ? 'red-bg' : 'green-bg' %>"><%= task.unscheduled ? "REACTIVE" : "SCHEDULED" %></p>
          <% if !task.completed && Date.today > task.end_date %>
            <p class="m-tag red-bg">OVERDUE</p>
          <% else %>
            <p class="m-tag <%= task.completed ? 'green-bg' : 'red-bg' %>"><%= task.completed ? 'COMPLETED' : 'INCOMPLETE' %></p>
          <% end %>
        </div>
      <% end %>
      <% if policy(task).new? %>
        <div class="menu-options dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          •••
        </div>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to "EDIT", edit_task_path(task), class: "dropdown-item" %>
          <%= link_to "DELETE", task_path(task), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete the task #{task.title}?"}, class: "dropdown-item" %>
        </div>
      <% end %>
    </section>
  <% end %>

  <div class="d-flex justify-content-between align-items-center pb-3">
    <h4 class="mb-0 d-title">COMPLETED TASKS</h4>
    <%= link_to 'VIEW STATS', stats_path, class: 'secondary-btn' %>
  </div>
  <section class="m-card">
    <%= column_chart @tasks_per_month, colors: ["rgba(1, 115, 222, 1)"], legend: false, height: "220px", discrete: true, label: "TODAY'S TASKS"  %>
  </section>

</div>

app/views/users/index.html.erb
<div class="w-view">
  <div class="new-network-card-cont mb-3">
    <% @technicians.each do |technician| %>
      <section class="new-network-card u-card p-4 <%= 'inactive' if !technician.active %>">
        <div class="">
          <h6 class="new-network-card__name mb-0" style="font-size: 14px;"><%= technician.first_name.upcase %></h6>
          <h6 class="new-network-card__name mb-1" style="font-size: 18px;"><%= technician.last_name.upcase %></h6>
          <p class="mb-1"><%= technician.phone %></p>
        </div>
        <% if technician.avatar.attached? %>
          <%= cl_image_tag technician.avatar.key, class: "avatar-large mb-1" %>
        <% else %>
          <div class="avatar-initials">
            <%= technician.initials %>
          </div>
        <% end %>
        <div>
          <% if technician.tasks.any? %>
            <p class="mb-0">ONGOING</p>
            <p class="mb-0">TASKS</p>
            <p class="text-green bold mb-0"><%= technician.tasks.where(completed: false).count %>/<%= technician.tasks.count %></p>
          <% else %>
            <p class="mb-0">NO ASSIGNED</p>
            <p class="mb-0">TASKS</p>
          <% end %>
        </div>
        <% if current_user.manager %>
          <div class="menu-options dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            •••
          </div>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "#{technician.active ? 'SET AS INACTIVE' : 'SET AS ACTIVE'}", user_status_path(technician), data: { turbo_method: :patch }, class: "dropdown-item" %>
          </div>
        <% end %>
      </section>
    <% end %>
  </div>
  <div class="pag-cont border-top mt-4">
    <div class="page-entry">
      <%= page_entries_info @technicians %>
    </div>
    <%= paginate @technicians %>
  </div>
</div>

<!------------- MOBILE ------------->
<!------------- VIEW ------------->
<!------------- BELOW ------------->

<div class="m-view">
  <h4 class="d-title mb-3">TECHNICIANS</h4>

  <div class="page-entry text-center mb-3">
    <%= page_entries_info @technicians %>
  </div>

  <% @technicians.each do |technician| %>
      <section class="new-network-card u-card p-4 <%= 'inactive' if !technician.active %>">
        <div class="">
          <h6 class="new-network-card__name mb-0" style="font-size: 14px;"><%= technician.first_name.upcase %></h6>
          <h6 class="new-network-card__name mb-1" style="font-size: 18px;"><%= technician.last_name.upcase %></h6>
          <p class="mb-1"><%= technician.phone %></p>
        </div>
        <% if technician.avatar.attached? %>
          <%= cl_image_tag technician.avatar.key, class: "avatar-large mb-1" %>
        <% else %>
          <div class="avatar-initials">
            <%= technician.initials %>
          </div>
        <% end %>
        <div>
          <% if technician.tasks.any? %>
            <p class="mb-0">ONGOING</p>
            <p class="mb-0">TASKS</p>
            <p class="text-green bold mb-0"><%= technician.tasks.where(completed: false).count %>/<%= technician.tasks.count %></p>
          <% else %>
            <p class="mb-0">NO ASSIGNED</p>
            <p class="mb-0">TASKS</p>
          <% end %>
        </div>
        <% if current_user.manager %>
          <div class="menu-options dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            •••
          </div>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "#{technician.active ? 'SET AS INACTIVE' : 'SET AS ACTIVE'}", user_status_path(technician), data: { turbo_method: :patch }, class: "dropdown-item" %>
          </div>
        <% end %>
      </section>
    <% end %>

</div>