config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :networks do
    member do
      post :increase
      post :decrease
    end
    resources :waterpoints, only: [:index, :new, :create, :edit, :update]
  end
  resources :tasks do
    patch :completed, on: :member
    collection do
      get :export, defaults: { format: :csv }
    end
    resources :comments, only: [:new, :create, :edit]
  end
  resources :waterpoints, only: [:destroy]
  resources :equipments do
    collection do
      get :export, defaults: { format: :csv }
    end
  end
  resources :services
  resources :comments, only: [:update, :destroy]
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'technicians', to: 'users#index', as: :technicians
  patch 'users/:id/user_status', to: 'users#user_status', as: :user_status
  get 'statistics', to: 'pages#stats', as: :stats
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_info_window.html.erb
<p><span>WATERPOINT:</span> <%= waterpoint.name.upcase %></p>
<p class="mb-3"><span>WATERPOINT TYPE:</span> <%= waterpoint.waterpoint_type.upcase %></p>
<p class="mb-0"><span>ADDRESS:</span> <%= waterpoint.address.upcase %></p>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "maintenance-tracker.png" %>
    <% end %>

    <% unless hide_nav %>
      <span class="ham-menu" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
        <i class="bi bi-list"></i>
      </span>
    <% end %>

    <div class="nav-options">
      <div class="collapse navbar-collapse <%= 'nav-seperator' if user_signed_in? %>" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <% if current_user.avatar.attached? %>
                <%= cl_image_tag current_user.avatar.key, class: "avatar-nav dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <div class="avatar-initials dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= current_user.initials.upcase %>
                </div>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <% if policy(Task).create? %>
                  <%= link_to "CREATE TASK", new_task_path, class: "dropdown-item" %>
                <% end %>
                <%= link_to "ACCOUNT", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "LOG OUT", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
            <li class="nav-info">
              <h6><%= current_user.full_name.upcase %></h6>
              <p><%= current_user.manager ? "MANAGER" : "TECHNICIAN" %></p>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="spacer"></div>
<% unless hide_nav %>
  <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header justify-content-end pb-0">
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <div class="nav-u">
        <% if user_signed_in? %>
          <li class="nav-item dropdown list-unstyled pb-2 d-flex justify-content-center">
            <% if current_user.avatar.attached? %>
              <%= cl_image_tag current_user.avatar.key, class: "avatar-nav dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <div class="avatar-initials dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.initials %>
              </div>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if policy(Task).create? %>
                <%= link_to "CREATE TASK", new_task_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "ACCOUNT", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "LOG OUT", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
          <li class="nav-info border-bottom pb-2">
            <h6 class="text-center"><%= current_user.full_name.upcase %></h6>
            <p class="text-center"><%= current_user.manager ? "MANAGER" : "TECHNICIAN" %></p>
          </li>
        <% end %>
      </div>
      <div class="">
        <% if policy(Task).create? %>
          <%= link_to 'CREATE TASK', new_task_path, class: 'primary-btn mb-2 mt-3' %>
        <% end %>
        <%= link_to root_path, class: "sidebar-link #{ 'active' if params[:action] == 'dashboard'  }" do %>
          <div>
            <%= image_tag 'home.png' %>
            <p>HOME</p>
          </div>
        <% end %>
<!--         <%#= link_to stats_path, class: "sidebar-link #{ 'active' if params[:action] == 'stats'  }" do %>
          <div>
            <%#= image_tag 'chart.png' %>
            <p>STATS</p>
          </div>
        <%# end %> -->
        <%= link_to tasks_path, class: "sidebar-link #{ 'active' if params[:controller] == 'tasks'  }" do %>
          <div>
            <%= image_tag 'task.png' %>
            <p>TASKS</p>
          </div>
        <% end %>
        <%= link_to networks_path, class: "sidebar-link #{ 'active' if params[:controller] == 'networks'  }" do %>
          <div>
            <%= image_tag 'network.png' %>
            <p>NETWORKS</p>
          </div>
        <% end %>
        <%= link_to technicians_path, class: "sidebar-link #{ 'active' if params[:controller] == 'users' && params[:action] == 'index'  }" do %>
          <div>
            <%= image_tag 'technician.png' %>
            <p>TECHNICIANS</p>
          </div>
        <% end %>
        <%= link_to equipments_path, class: "sidebar-link #{ 'active' if params[:controller] == 'equipments'  }" do %>
          <div>
            <%= image_tag 'equipment.png' %>
            <p>EQUIPMENT</p>
          </div>
        <% end %>
        <%= link_to services_path, class: "sidebar-link #{ 'active' if params[:controller] == 'services'  }" do %>
          <div>
            <%= image_tag 'service.png' %>
            <p>SERVICES</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
  <div class="">
    <% if policy(Task).create? %>
      <%= link_to 'CREATE TASK', new_task_path, class: 'primary-btn mb-2' %>
    <% end %>
    <%= link_to root_path, class: "sidebar-link #{ 'active' if params[:action] == 'dashboard'  }" do %>
      <div>
        <%= image_tag 'home.png' %>
        <p>HOME</p>
      </div>
    <% end %>
<!--     <%#= link_to stats_path, class: "sidebar-link #{ 'active' if params[:action] == 'stats'  }" do %>
      <div>
        <%#= image_tag 'chart.png' %>
        <p>STATS</p>
      </div>
    <%# end %> -->
    <%= link_to tasks_path, class: "sidebar-link #{ 'active' if params[:controller] == 'tasks'  }" do %>
      <div>
        <%= image_tag 'task.png' %>
        <p>TASKS</p>
      </div>
    <% end %>
    <%= link_to networks_path, class: "sidebar-link #{ 'active' if params[:controller] == 'networks'  }" do %>
      <div>
        <%= image_tag 'network.png' %>
        <p>NETWORKS</p>
      </div>
    <% end %>
    <%= link_to technicians_path, class: "sidebar-link #{ 'active' if params[:controller] == 'users' && params[:action] == 'index'  }" do %>
      <div>
        <%= image_tag 'technician.png' %>
        <p>TECHNICIANS</p>
      </div>
    <% end %>
    <%= link_to equipments_path, class: "sidebar-link #{ 'active' if params[:controller] == 'equipments'  }" do %>
      <div>
        <%= image_tag 'equipment.png' %>
        <p>EQUIPMENT</p>
      </div>
    <% end %>
    <%= link_to services_path, class: "sidebar-link #{ 'active' if params[:controller] == 'services'  }" do %>
      <div>
        <%= image_tag 'service.png' %>
        <p>SERVICES</p>
      </div>
    <% end %>
  </div>
</div>